language: objective-c
osx_image: xcode8.3
xcode_project: UIFontComplete.xcodeproj # path to your xcodeproj folder
xcode_scheme: UIFontComplete

script:
  - xcodebuild test -scheme UIFontComplete -sdk iphonesimulator -destination 'id=47B400BF-57B2-4119-9811-6359FF86A51D'
after_success:
  - bash <(curl -s https://codecov.io/bash)
