language: objective-c
osx_image: xcode8.3
xcode_project: UIFontComplete.xcodeproj # path to your xcodeproj folder
xcode_scheme: UIFontComplete

script:
  - xcodebuild test -scheme UIFontComplete -sdk iphonesimulator -destination 'id=375B606D-0484-4067-9E45-7697A3860886'
after_success:
  - bash <(curl -s https://codecov.io/bash)
